# MPV Music Configuration

[profile music]
no-video
ao=pulse
volume=100
save-position-on-quit
input-ipc-server=/tmp/mpvsocket
shuffle=yes
loop=no

[extension-mp3]
profile=music

[extension-flac]
profile=music

[extension-wav]
profile=music

[extension-ogg]
profile=music

[extension-m4a]
profile=music

[extension-aac]
profile=music

[protocol-ytdl]
profile=music
[protocol-http]
profile=music

[protocol-https]
profile=music